server:
  port: 8080

spring:
  application:
    name: ${APPLICATION_NAME:mailing_service}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka/}