server:
  port: 8080

spring:
  application:
    name: ${APPLICATION_NAME:mailing-service}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: mailing-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.auth_service.dto, com.mailing_service.dto"#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        spring.json.fail-on-unknown-properties: false
        spring.json.value.default.type: com.mailing_service.dto.MailDto  #!!!!!!!!!!!!!!!!!!!!!!!!!!!
        spring.json.type.mapping: com.auth_service.dto.MailDto:com.mailing_service.dto.MailDto #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    listener:
      ack-mode: manual
      concurrency: 3
      type: single
      missing-topics-fatal: false
    retry:
      topic:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}!!!!!!!!!!!!!!!
    password: ${MAIL_PASSWORD}!!!!!!!!!!!!!!!
    test-connection: true
    properties:
      mail:
        smtp:
          mail.smtp.connectiontimeout: 5000
          mail.smtp.timeout: 5000
          mail.smtp.writetimeout: 5000
          auth: true
          starttls:
            enable: true
    sender:
      email: no-reply@gmail.com

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka/}

kafka-topics:
  mailing: mailing